version: '3.9'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    restart: always
    ports:
      - 10000:10000
    volumes:
      - ./azurite:/workspace
    command: "azurite --loose --blobHost 127.0.0.1 --blobPort 10000 --location /workspace --debug /workspace/debug.log"
